[Api] Story 89902 - Admin Create Group
nhsengland/futurenhs pull request #142
Opened 2022-05-05 21:16 UTC by Matt-Beldon-CDS

[+] Adds endpoint to allow an admin to create a group

2022-05-09 08:27 UTC, Tim-Hunt-CDS requested changes

2022-05-09 08:27 UTC, Tim-Hunt-CDS commented on futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
> +            await using var transaction = connection.BeginTransaction();
good, nice to see we're using transactions for this sort of work

2022-05-09 08:27 UTC, Tim-Hunt-CDS commented on futurenhs.api/FutureNHS.Api/Services/Admin/AdminGroupService.cs
> +            var groupValidationResult = await groupValidator.ValidateAsync(group, cancellationToken);
Slug is being passed into the Api but theres no check to ensure its unique and the DB doesn't have a unique key constraint on Slug.

2022-05-09 08:49 UTC, Tim-Hunt-CDS approved these changes

2022-05-09 08:50 UTC, Tim-Hunt-CDS commented on futurenhs.api/FutureNHS.Api/Services/Admin/AdminGroupService.cs
> +            var groupValidationResult = await groupValidator.ValidateAsync(group, cancellationToken);
Ignore this, the unique constraint is set on the index

2022-05-10 11:06 UTC, ReallySmall approved these changes

2022-05-10 11:07 UTC, merged