Clearer discussion posts #351
nhsengland/futurenhs pull request #358
Opened 2022-09-14 14:21 UTC by jpmaHub

<img width="1303" alt="Screenshot 2022-09-14 at 15 20 19" src="https://user-images.githubusercontent.com/17250560/190180678-0f170635-d175-4d81-b473-aaa789d59b95.png">

2022-09-20 15:01 UTC, tim-hunt commented
I believe from the discussion on the issue: https://github.com/nhsengland/futurenhs/issues/351 they also wanted the creator and number of comments displaying on the card too, so like this one but with the bar at the bottom like you have it 
![image](https://user-images.githubusercontent.com/108523116/191293648-87e602bc-2e90-438d-b8c7-a5dce668375f.png)

2022-09-20 15:10 UTC, tim-hunt requested changes
I believe from the discussion on the issue: https://github.com/nhsengland/futurenhs/issues/351 they also wanted the creator and number of comments displaying on the card too, so like this one but with the bar at the bottom like you have it 
![image](https://user-images.githubusercontent.com/108523116/191295878-793737a7-e844-47af-93a0-c949c13255a0.png)

2022-09-21 08:25 UTC, jpmaHub commented
<img width="1332" alt="Screenshot 2022-09-21 at 09 23 09" src="https://user-images.githubusercontent.com/17250560/191454432-ad7c4058-f599-4142-95e4-7167ee34ae2d.png">

2022-09-21 08:27 UTC, tim-hunt approved these changes

2022-09-21 08:31 UTC, merged