Checks whether requested content requires deserialization before retu…
nhsengland/futurenhs pull request #37
Opened 2022-04-05 11:24 UTC by JackWCDS

…rning data to main web api

2022-04-06 09:20 UTC, Matt-Beldon-CDS requested changes

2022-04-06 09:20 UTC, Matt-Beldon-CDS commented on futurenhs.content.api/Umbraco9ContentApi.Core/Converters/JsonContentConverter.cs
> +                if (obj != null)
obj is not null

2022-04-06 23:19 UTC, Tim-Hunt-CDS reviewed
What’s the use case for this?

2022-04-07 09:16 UTC, JackWCDS commented
> What’s the use case for this?

Hey Tim. Where we store actual page content as json we need to ensure it's in the correct format for F/E consumption

2022-04-07 10:11 UTC, Matt-Beldon-CDS approved these changes

2022-04-08 10:30 UTC, merged