Pending members
nhsengland/futurenhs pull request #389
Opened 2022-12-16 14:52 UTC by rio-k9

2022-12-16 15:29 UTC, tim-hunt requested changes

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
> +                @$"
Please format this to match the other SQL queries as they are more readbale

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
> +        public async Task<GroupInvite> GetGroupInviteByUserAsync(Guid userId, Guid groupId, CancellationToken cancellationToken = default)
Can the name of this method be clearer? eg GetGroupInviteForUserIdAsync

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/DataAccess/Database/Write/GroupCommand.cs
> +                    WHERE       gi.Id = @Id;";
Need to check if deleted or not

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/Services/GroupService.cs
> +        // private readonly IRegistrationCommand _registrationCommand;
remove rather than commenting out

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/Services/GroupService.cs
> +            // IRegistrationCommand registrationCommand,
remove rather than commenting out

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/Services/GroupService.cs
> +            // _registrationCommand = registrationCommand ?? throw new ArgumentNullException(nameof(registrationCommand));
remove rather than commenting out

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/Services/GroupService.cs
>              if (string.IsNullOrWhiteSpace(slug)) throw new ArgumentOutOfRangeException(nameof(slug));
var userCanPerformAction = await _permissionsService.UserCanPerformActionAsync(userId, slug, GroupViewRole, cancellationToken); 

I know you didn't write this but can the role be changed to GroupEditRole please as GroupView is not correct

2022-12-16 15:29 UTC, tim-hunt commented on futurenhs.api/FutureNHS.Api/Services/RegistrationService.cs
> +            // var userCanPerformAction = await _permissionsService.UserCanPerformActionAsync(userId, groupInviteId, GroupInviteDeleteRole, cancellationToken);
Why is this commented out? at the moment anyone can delete any platform invite

2023-02-03 11:42 UTC, sjoswald approved these changes

2023-02-03 11:42 UTC, merged